name: Build and publish

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          always-auth: true
          cache: npm
          cache-dependency-path: package-lock.json
          node-version: 16
          registry-url: https://npm.pkg.github.com/

      - name: Download dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Run lint
      #   run: npm run lint

      - name: Compile Typescript
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: version
        run: echo "::set-output name=version::$(echo $(npm view @ajar-online/functions-differ version))"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          MSG_MINIMAL: true
          SLACK_COLOR: ${{ job.status }}
          SLACK_FOOTER: ${{ steps.version.outputs.version }}
          SLACK_ICON: https://emojis.slackmojis.com/emojis/images/1556810896/5673/octopus_deploy.png
          SLACK_MESSAGE: Release Completed
          SLACK_TITLE: "@ajar-online/functions-differ"
          SLACK_USERNAME: GitHub
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          MSG_MINIMAL: true
          SLACK_COLOR: ${{ job.status }}
          SLACK_FOOTER: ""
          SLACK_ICON: https://emojis.slackmojis.com/emojis/images/1556810896/5673/octopus_deploy.png
          SLACK_MESSAGE: Release Failed
          SLACK_TITLE: "@ajar-online/functions-differ"
          SLACK_USERNAME: GitHub
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - if: ${{ cancelled() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          MSG_MINIMAL: true
          SLACK_COLOR: ${{ job.status }}
          SLACK_FOOTER: ""
          SLACK_ICON: https://emojis.slackmojis.com/emojis/images/1556810896/5673/octopus_deploy.png
          SLACK_MESSAGE: Release Canceled
          SLACK_TITLE: "@ajar-online/functions-differ"
          SLACK_USERNAME: GitHub
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
